name: Update UFAG feed

on:
  schedule:
    # Runs every weekday at 05:00 UTC (~07:00 DK summer time). Adjust as needed.
    - cron: "0 5 * * 1-5"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip

      - name: Fetch & build ufag_jobs.json
        env:
          SOURCE_URL: ${{ secrets.SOURCE_URL }}
          SOURCE_TYPE: ${{ vars.SOURCE_TYPE }}
          CSV_DELIMITER: ${{ vars.CSV_DELIMITER }}
          CSV_ENCODING: ${{ vars.CSV_ENCODING }}
          CSV_TITLE: ${{ vars.CSV_TITLE }}
          CSV_COMPANY: ${{ vars.CSV_COMPANY }}
          CSV_LOCATION: ${{ vars.CSV_LOCATION }}
          CSV_SOURCE: ${{ vars.CSV_SOURCE }}
          CSV_URL: ${{ vars.CSV_URL }}
          CSV_POSTED_AT: ${{ vars.CSV_POSTED_AT }}
          CSV_DEADLINE: ${{ vars.CSV_DEADLINE }}
          CSV_IS_NEW: ${{ vars.CSV_IS_NEW }}
        run: |
          python update_feed.py

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add ufag_jobs.json
            git commit -m "chore: auto-update ufag_jobs.json"
            git push
          else
            echo "No changes to commit"
          fi
